using System;
using System.Globalization;

namespace Irihi.Lolita;

/// <summary>
/// Represents an i18n manager that can switch the active culture and expose
/// observable string properties for all resource keys.
/// </summary>
/// <remarks>
/// Implementations of this interface are generated by the Irihi.Lolita source
/// generator for classes annotated with <see cref="LolitaManagerAttribute"/>.
/// The singleton instance of the generated class is exposed via a static
/// <c>Instance</c> property.
/// </remarks>
public interface ILolitaManager
{
    /// <summary>
    /// Switches all observable string properties to the resource values for
    /// <paramref name="culture"/>, falling back to the parent culture and then
    /// to the default (invariant) culture if an exact match is not found.
    /// </summary>
    /// <param name="culture">The target culture.  A <c>null</c> value is treated
    /// as <see cref="CultureInfo.InvariantCulture"/>.</param>
    void UpdateCulture(CultureInfo culture);

    /// <summary>
    /// Returns the <see cref="IObservable{T}"/> that emits the current localized
    /// string for the given resource <paramref name="key"/>, or <c>null</c> when
    /// the key is not found.
    /// </summary>
    /// <param name="key">The raw resource key string (e.g. <c>"App_Title"</c>).</param>
    IObservable<string>? GetObservable(string key);
}
