using System.Globalization;

namespace Irihi.Lolita;

/// <summary>
/// A thread-safe, mutable store for runtime-loaded localization resources.
/// </summary>
/// <remarks>
/// <para>
/// Each <see cref="ILolitaManager"/> implementation generated by the Lolita
/// source generator holds one instance of this class.  Call
/// <see cref="ILolitaManager.AddResources"/> to populate it; the manager
/// will consult it in <c>UpdateCulture</c> after the compile-time (embedded)
/// resources, so runtime entries take precedence over baked-in ones.
/// </para>
/// <para>
/// You can also instantiate this class independently when you need to
/// aggregate resources from multiple sources before handing them to a manager.
/// </para>
/// </remarks>
public sealed class LolitaRuntimeResources
{
#if NET9_0_OR_GREATER
    private readonly Lock _lock = new();
#else
    private readonly object _lock = new();
#endif

    private volatile Dictionary<CultureInfo, IReadOnlyDictionary<string, string>> _store = new();

    /// <summary>
    /// Adds or updates resource entries for the given culture.
    /// </summary>
    /// <remarks>
    /// Entries in <paramref name="resources"/> are merged into any existing
    /// entries for <paramref name="culture"/>; existing keys are overwritten.
    /// Pass <see cref="CultureInfo.InvariantCulture"/> to target the
    /// invariant / fallback culture.
    /// </remarks>
    /// <param name="culture">The culture. Must not be <c>null</c>.</param>
    /// <param name="resources">
    /// The key/value pairs to add.  Must not be <c>null</c>.
    /// </param>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="culture"/> or <paramref name="resources"/> is <c>null</c>.
    /// </exception>
    public void Add(CultureInfo culture, IReadOnlyDictionary<string, string> resources)
    {
        ArgumentNullException.ThrowIfNull(culture);
        ArgumentNullException.ThrowIfNull(resources);

        lock (_lock)
        {
            var newStore = new Dictionary<CultureInfo, IReadOnlyDictionary<string, string>>(_store);

            if (newStore.TryGetValue(culture, out var existing))
            {
                var merged = new Dictionary<string, string>(existing);
                foreach (var kv in resources)
                    merged[kv.Key] = kv.Value;

                newStore[culture] = merged;
            }
            else
            {
                newStore[culture] = new Dictionary<string, string>(resources);
            }

            _store = newStore;
        }
    }

    /// <summary>
    /// Resolves the best-matching resource dictionary for <paramref name="culture"/>
    /// using the same fallback chain as <c>UpdateCulture</c>:
    /// exact culture → two-letter ISO language → invariant culture.
    /// </summary>
    /// <param name="culture">The target culture.  Must not be <c>null</c>.</param>
    /// <returns>
    /// A snapshot copy of the matched entries, or <c>null</c> when no entry
    /// exists for the culture or any of its fallbacks.
    /// </returns>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="culture"/> is <c>null</c>.
    /// </exception>
    public IReadOnlyDictionary<string, string>? Resolve(CultureInfo culture)
    {
        ArgumentNullException.ThrowIfNull(culture);

        var store = _store;

        if (store.TryGetValue(culture, out var dict))
            return dict;

        if (culture.Name.Length > 0)
        {
            var twoLetter = culture.TwoLetterISOLanguageName;
            if (twoLetter != culture.Name &&
                store.TryGetValue(CultureInfo.GetCultureInfo(twoLetter), out dict))
                return dict;
        }

        if (store.TryGetValue(CultureInfo.InvariantCulture, out dict))
            return dict;

        return null;
    }
}
