using System.Globalization;

namespace Irihi.Lingua;

/// <summary>
/// Represents an i18n manager that can switch the active culture and expose
/// observable string properties for all resource keys.
/// </summary>
/// <remarks>
/// Implementations of this interface are generated by the Irihi.Lingua source
/// generator for classes annotated with <see cref="LinguaManagerAttribute"/>.
/// The singleton instance of the generated class is exposed via a static
/// <c>Instance</c> property.
/// </remarks>
public interface ILinguaManager
{
    /// <summary>
    /// Gets the culture that was last passed to <see cref="UpdateCulture"/>.
    /// The initial value before <see cref="UpdateCulture"/> is first called
    /// is <see cref="CultureInfo.InvariantCulture"/>.
    /// </summary>
    CultureInfo CurrentCulture { get; }

    /// <summary>
    /// Switches all observable string properties to the resource values for
    /// <paramref name="culture"/>, falling back to the parent culture and then
    /// to the default (invariant) culture if an exact match is not found.
    /// </summary>
    /// <param name="culture">The target culture.  A <c>null</c> value is treated
    /// as <see cref="CultureInfo.InvariantCulture"/>.</param>
    void UpdateCulture(CultureInfo culture);

    /// <summary>
    /// Returns the <see cref="IObservable{T}"/> that emits the current localized
    /// string for the given resource <paramref name="key"/>, or <c>null</c> when
    /// the key is not found.
    /// </summary>
    /// <param name="key">The raw resource key string (e.g. <c>"App_Title"</c>).</param>
    IObservable<string?>? GetObservable(string key);

    /// <summary>
    /// Adds or overrides resource strings for the given culture at runtime.
    /// </summary>
    /// <remarks>
    /// Entries supplied here take precedence over compile-time (embedded) resources
    /// when <see cref="UpdateCulture"/> is next called.  This allows loading new
    /// cultures or patching existing ones without recompiling the assembly.
    /// Calling this method does <em>not</em> immediately update observable values;
    /// call <see cref="UpdateCulture"/> afterwards to apply the change.
    /// </remarks>
    /// <param name="culture">
    /// The target culture (e.g. <c>new CultureInfo("ja-JP")</c>).
    /// Use <see cref="CultureInfo.InvariantCulture"/> for the invariant/default culture.
    /// </param>
    /// <param name="resources">
    /// The key/value pairs to add.  Must not be <c>null</c>.
    /// </param>
    void AddResources(CultureInfo culture, IReadOnlyDictionary<string, string> resources);
}